analytics: {}
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.641047
  lightness: 0.908613
  rhythmicContrast: 0.677702
  saturation: 0.038613
cta: {}
layout_spectrum: 0.2780059480573982
name: startuplife
opengraph: {}
purpose: []
typography_spectrum: 0.9992824189830571
